name: build
on:
  push:
    paths:
      - '/bots/poharan/**.rs'
      - '/bots/poharan/**.toml'
      - '/bots/poharan/**.lock'
  pull_request:
    paths:
      - '/bots/poharan/**.rs'
      - '/bots/poharan/**.toml'
      - '/bots/poharan/**.lock'
  workflow_dispatch:

jobs:
  build:
    name: Build Poharan Release
    timeout-minutes: 30
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --package bns-poharan --bin bns-poharan