name: build
on:
  push:
    paths:
      - '/bots/aerodrome-exp/**.rs'
      - '/bots/aerodrome-exp/**.toml'
      - '/bots/aerodrome-exp/**.lock'
  pull_request:
    paths:
      - '/bots/aerodrome-exp/**.rs'
      - '/bots/aerodrome-exp/**.toml'
      - '/bots/aerodrome-exp/**.lock'

jobs:
  build_and_test:
    name: Build Aerodrome Exp Release
    timeout-minutes: 30
    strategy:
      matrix:
        # macos-latest is too expensive for monthly limit, don't build on it while repo is private
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --package bns-aerodrome-exp --bin bns-aerodrome-exp