name: 'build - macros'
on:
  push:
    paths:
      - '/macros/**.rs'
      - '/macros/**.toml'
      - '/macros/**.lock'
  pull_request:
    paths:
      - '/macros/**.rs'
      - '/macros/**.toml'
      - '/macros/**.lock'
  workflow_dispatch:

jobs:
  build:
    name: Build Macro Release
    timeout-minutes: 30
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --package bns-macros --bin bns-macros